// <auto-generated />
using AlphaNET.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlphaNET.Server.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlphaNET.Server.User", b =>
                {
                    b.Property<string>("RealIp")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("VirtualIp")
                        .IsRequired();

                    b.HasKey("RealIp");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
